"""Add is_read field to Notification model

Revision ID: 0856f2b92715
Revises: 32b8fceac6a4
Create Date: 2025-04-17 07:15:15.829503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0856f2b92715'
down_revision = '32b8fceac6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
