"""Add ProjectAccommodationRequest table

Revision ID: 116f7d3e57b7
Revises: daa295f22c03
Create Date: 2025-04-08 23:56:14.420432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116f7d3e57b7'
down_revision = 'daa295f22c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_accommodation_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('stay_from', sa.Date(), nullable=False),
    sa.Column('stay_to', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=1), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('offer_letter_path', sa.String(length=200), nullable=True),
    sa.Column('id_proof_path', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('hostel_allotted', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['custom_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hostel_allotted'], ['hostel.hostel_no'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))

    op.drop_table('project_accommodation_request')
    # ### end Alembic commands ###
