"""Add payment_details field to GuestRoomBooking

Revision ID: 1e6a9be35d8a
Revises: 0856f2b92715
Create Date: 2025-04-18 06:49:25.105186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '1e6a9be35d8a'
down_revision = '0856f2b92715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_room_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_details', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_room_booking', schema=None) as batch_op:
        batch_op.drop_column('payment_details')

    # ### end Alembic commands ###
