"""Initial migration.

Revision ID: 55442da7a900
Revises: 
Create Date: 2025-03-05 16:15:05.169273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55442da7a900'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('batch_no', sa.String(length=20), nullable=False),
    sa.Column('number_of_students', sa.Integer(), nullable=True),
    sa.Column('number_of_girls', sa.Integer(), nullable=True),
    sa.Column('number_of_boys', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('batch_no')
    )
    op.create_table('custom_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hostel',
    sa.Column('hostel_no', sa.String(length=20), nullable=False),
    sa.Column('hostel_name', sa.String(length=100), nullable=True),
    sa.Column('hostel_type', sa.String(length=50), nullable=True),
    sa.Column('num_floors', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('hostel_no')
    )
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('signature', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['custom_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('caretaker',
    sa.Column('caretaker_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hostel_no', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['hostel_no'], ['hostel.hostel_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['custom_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('caretaker_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('caretaker_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caretaker_id', sa.Integer(), nullable=True),
    sa.Column('hostel_no', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caretaker_id'], ['custom_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hostel_no'], ['hostel.hostel_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('faculty_phone', sa.String(length=10), nullable=False),
    sa.Column('is_hod', sa.Boolean(), nullable=True),
    sa.Column('signature', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['custom_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faculty_id'),
    sa.UniqueConstraint('faculty_phone')
    )
    op.create_table('room',
    sa.Column('room_no', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('hostel_no', sa.String(length=20), nullable=True),
    sa.Column('room_occupancy', sa.Integer(), nullable=True),
    sa.Column('current_occupancy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_no'], ['hostel.hostel_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_no')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('student_phone', sa.String(length=10), nullable=True),
    sa.Column('student_roll', sa.String(length=15), nullable=True),
    sa.Column('student_year', sa.Integer(), nullable=True),
    sa.Column('student_room_no', sa.String(length=20), nullable=True),
    sa.Column('student_batch', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['custom_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_roll')
    )
    op.create_table('internship_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('affiliation', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('faculty_mentor', sa.String(length=100), nullable=False),
    sa.Column('faculty_email', sa.String(length=100), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('id_card', sa.String(length=100), nullable=False),
    sa.Column('official_letter', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('faculty_signature_id', sa.Integer(), nullable=True),
    sa.Column('hod_signature_id', sa.Integer(), nullable=True),
    sa.Column('admin_signature_id', sa.Integer(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_signature_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['faculty_signature_id'], ['faculty.faculty_id'], ),
    sa.ForeignKeyConstraint(['hod_signature_id'], ['faculty.faculty_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warden',
    sa.Column('warden_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('hostel_no', sa.String(length=20), nullable=False),
    sa.Column('is_chief', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostel_no'], ['hostel.hostel_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warden_id'),
    sa.UniqueConstraint('faculty_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warden')
    op.drop_table('internship_application')
    op.drop_table('student')
    op.drop_table('room')
    op.drop_table('faculty')
    op.drop_table('caretaker_history')
    op.drop_table('caretaker')
    op.drop_table('admin')
    op.drop_table('hostel')
    op.drop_table('custom_user')
    op.drop_table('batch')
    # ### end Alembic commands ###
