"""Add relationship between GuestRoomBooking and Remark

Revision ID: 8da188e9e356
Revises: d41b6af8a14f
Create Date: 2025-04-19 06:54:31.414995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da188e9e356'
down_revision = 'd41b6af8a14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_room_booking', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_room_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
