"""Fix remarks field in GuestRoomBooking

Revision ID: 928859249670
Revises: 8da188e9e356
Create Date: 2025-04-19 10:23:09.612528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928859249670'
down_revision = '8da188e9e356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_room_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_room_booking', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
