"""Add dummy tables for batch allocation

Revision ID: a8e1c8acf039
Revises: 55442da7a900
Create Date: 2025-03-18 10:13:48.941372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e1c8acf039'
down_revision = '55442da7a900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=20), nullable=False),
    sa.Column('number_of_students', sa.Integer(), nullable=False),
    sa.Column('number_of_boys', sa.Integer(), nullable=False),
    sa.Column('number_of_girls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no')
    )
    op.create_table('dummy_hostel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostel_no', sa.String(length=20), nullable=False),
    sa.Column('hostel_name', sa.String(length=100), nullable=False),
    sa.Column('hostel_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostel_no')
    )
    op.create_table('dummy_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('number_of_students', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['dummy_batch.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['dummy_hostel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_allocation')
    op.drop_table('dummy_hostel')
    op.drop_table('dummy_batch')
    # ### end Alembic commands ###
