"""Add Notification table

Revision ID: b11d386f399c
Revises: fdb8d2fbf569
Create Date: 2025-04-17 05:42:32.756633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11d386f399c'
down_revision = 'fdb8d2fbf569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['guest_room_booking.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['admin.admin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_room_booking', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'room', ['room_no'], ['room_no'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_room_booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('notification')
    # ### end Alembic commands ###
