"""Add GuestRoomBooking table

Revision ID: d3c0bbfa21ed
Revises: 175602dceeb1
Create Date: 2025-03-25 21:02:40.004568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c0bbfa21ed'
down_revision = '175602dceeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_room_booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('total_guests', sa.Integer(), nullable=False),
    sa.Column('guests_male', sa.Integer(), nullable=False),
    sa.Column('guests_female', sa.Integer(), nullable=False),
    sa.Column('guest_names', sa.Text(), nullable=False),
    sa.Column('relation_with_applicant', sa.Text(), nullable=False),
    sa.Column('guest_address', sa.Text(), nullable=False),
    sa.Column('guest_contact', sa.Text(), nullable=False),
    sa.Column('guest_email', sa.Text(), nullable=True),
    sa.Column('purpose_of_visit', sa.Text(), nullable=False),
    sa.Column('room_category', sa.Text(), nullable=False),
    sa.Column('date_arrival', sa.Date(), nullable=False),
    sa.Column('time_arrival', sa.Time(), nullable=False),
    sa.Column('date_departure', sa.Date(), nullable=False),
    sa.Column('time_departure', sa.Time(), nullable=False),
    sa.Column('accommodation_by', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('hostel_no', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['custom_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostel_no'], ['hostel.hostel_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_room_booking')
    # ### end Alembic commands ###
