"""Add designation to Admin

Revision ID: daa295f22c03
Revises: ded1fa4d612b
Create Date: 2025-03-25 21:16:34.576926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa295f22c03'
down_revision = 'ded1fa4d612b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=False, server_default=''))

    # Remove the server_default after the column is added
    op.alter_column('admin', 'designation', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('designation')

    # ### end Alembic commands ###