"""Add created_at column to internship_application

Revision ID: db47248347a7
Revises: 116f7d3e57b7
Create Date: 2025-04-09 12:31:52.161446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db47248347a7'
down_revision = '116f7d3e57b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internship_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internship_application', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
