"""Add guest_rooms to Hostel

Revision ID: ded1fa4d612b
Revises: d3c0bbfa21ed
Create Date: 2025-03-25 21:06:26.838095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded1fa4d612b'
down_revision = 'd3c0bbfa21ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_rooms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.drop_column('guest_rooms')

    # ### end Alembic commands ###
