"""Add phone and signature fields to caretaker

Revision ID: f2ae709964cb
Revises: db47248347a7
Create Date: 2025-04-13 18:27:44.144469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ae709964cb'
down_revision = 'db47248347a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caretaker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('project_accommodation_request', schema=None) as batch_op:
        batch_op.alter_column('otp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_accommodation_request', schema=None) as batch_op:
        batch_op.alter_column('otp',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('caretaker', schema=None) as batch_op:
        batch_op.drop_column('signature')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
