"""Add Guest model and related changes

Revision ID: fdb8d2fbf569
Revises: f2ae709964cb
Create Date: 2025-04-13 20:43:56.799605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb8d2fbf569'
down_revision = 'f2ae709964cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['custom_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    # ### end Alembic commands ###
